server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_media_db?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
custom:
  db:
    init-scripts:
      - classpath:data.sql
